article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),

]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Author ")
    title = models.CharField(max_length = 50,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Date Created")
    article_image = models.FileField(blank = True,null = True,verbose_name="Add Photos to Article")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "Name")
    comment_content = models.CharField(max_length = 200,verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "User name")
    password = forms.CharField(label = "Password",widget = forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "User name")
    password = forms.CharField(max_length=20,label = "Password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="PVerify Password",widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords Don't Match")

        values = {
            "username" : username,
            "password" : password
        }
        return values

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request,"Article created successfully")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})


def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})


@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request,"Article updated successfully")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})


@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Article Deleted Successfully")

    return redirect("article:dashboard")


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout



# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"Successfully Register ...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)



def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Username or Password Incorrect")
            return render(request,"login.html",context)

        messages.success(request,"Successfully Logged In")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)


def logoutUser(request):
    logout(request)
    messages.success(request,"Successfully Logged Out")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}


{% block body %}

<h3>About Us</h3>
<hr>

<p>
        This a sample website for creating and sharing blog post
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add Article</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class ="row">

        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Articles</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %}
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Search...">
              <button type="submit" class="btn btn-danger">Search</button>
            </form>
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>

      <!-- Author -->
      <p class="lead">

        Published by {{article.author.username}}
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}


      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Read More</a>
      <hr>

        </div>
      </div>
      </div>

{% endfor %}


{% else %}
<div class ="row">

    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
   Article Not Found
</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Control Board</h3>
<hr>
<p>
    Welcome, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Add Article </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">History</th>
            <th scope="col">Update</th>
            <th scope="col">Clear</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Update</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Clear</a> </td>

          </tr>
          {% endfor %}

        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    You have no articles yet ...

</div>
{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">

       Published by {{article.author.username}}
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}


      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>Comments</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}


      {% else %}
      <div class ="alert alert-danger">
        Be the first to write a review!
      </div>
      {% endif %}

      <div class="card my-4">
          <h5 class="card-header">Add Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Name">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Add</button>
            </form>
          </div>
        </div>
        </div>

      </div>



{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index'  %}">Django Blog</a>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:articles'  %}">Articles</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'about'  %}">About Us</a>
            </li>

          </ul>

          <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard'  %}">Admin Dashboard</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout'  %}">Log out</a>
          </li>
          {% else %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:login'  %}">Sign in</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register'  %}">Register</a>
          </li>
          {% endif %}


          </ul>
        </div>


</nav>

templates/includes/posttemplate.html
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4">Post Title</h1>

      <!-- Author -->
      <p class="lead">
        by
        <a href="#">Start Bootstrap</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>Posted on January 1, 2018 at 12:00 PM</p>

      <hr>

      <!-- Preview Image -->
      <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

      <hr>

      <!-- Post Content -->
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

      <blockquote class="blockquote">
        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer class="blockquote-footer">Someone famous in
          <cite title="Source Title">Source Title</cite>
        </footer>
      </blockquote>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

      <hr>

      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
          <form>
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>

      <!-- Single Comment -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div>

      <!-- Comment with nested comments -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

        </div>
      </div>

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
        </div>
      </div>

    </div>

  </div>

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
        <h3>Welcome to Django Blog</h3>
</div>


<p>
        {% if request.user.is_authenticated %}
                Welcome, {{request.user.username}}
        {% else %}
                Unassigned
        {% endif %}

</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Django Blog</title>
</head>
<body>
        {% include "includes/navbar.html" %}



        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">

            {% if messages %}

                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}

                {% endif %}
            {% block body %}

            {% endblock body %}

        </div>


      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Sign in</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Sign in</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Sign in</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Update Article</button>
        </form>
    </div>
  </div>


{% endblock body %}